# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDtesttools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usersinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=20)),
                ('uid', models.CharField(max_length=30)),
                ('actionid', models.CharField(max_length=3)),
                ('itemtype', models.CharField(max_length=3)),
                ('utype', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Employes',
        ),
    ]
